rootタスクに対する変更を禁止するように修正
waderaku/pomodoro-backend pull request #52
Opened 2022-07-24 23:31 UTC by waderaku

2022-07-24 23:32 UTC, waderaku commented
![image](https://user-images.githubusercontent.com/64270877/180670332-f20631b4-42cb-464a-b94d-83d831672902.png)

2022-07-30 05:58 UTC, yotaro-shimose requested changes

2022-07-30 05:58 UTC, yotaro-shimose commented on pomodoro-timer/app/usecase/service/update_task_service.py
> +        raise UpdateRootTaskException()
このあたり定数用意なかったでしたっけ！あるいは僕が勝手にTaskクラスのファイルに作ったかもしれないのでそれをつかってほしい！

2022-07-30 06:58 UTC, yotaro-shimose approved these changes

2022-07-30 06:58 UTC, merged